### GET ONE

GET http://localhost:5000/clients/1
### GET ONE With details

GET http://localhost:5000/clients/1?expand=ClientType

### GET MANY

GET http://localhost:5000/clients

### GET MANY WITH FILTER
GET http://localhost:5000/clients?condition=name%20eq%20Tennis

### GET MANY WITH ORDERING

GET http://localhost:5000/clients?order=name


### GET MANY with details

GET http://localhost:5000/clients?expand=ClientType

### DELETE

DELETE http://localhost:5000/clients/3

### CREATE

POST http://localhost:5000/clients

  {
    "Name": "Smoking Pant"
  }